name: Build bindings for Alpine

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:${{ matrix.node }}-alpine
    strategy:
      fail-fast: false
      matrix:
        node:
          - 14
          - 16
          - 18
          - 19
          - 20

    steps:
      - name: Install Alpine build tools
        run: apk add --no-cache python3 make git gcc g++

      - name: Update NPM
        run: npm i npm -g

      - uses: actions/checkout@v3

      - name: Install packages
        run: npm install --unsafe-perm
        env:
          SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true

      - name: Run tests
        run: npm test

      - uses: actions/upload-artifact@v3
        if: github.event_name != 'pull_request'
        with:
          name: ${{ matrix.node }}
          path: vendor/
